-- written by GAIA using Notepad++
CREATE TABLE IF NOT EXISTS Sapiens_DBUpdates (Name TEXT PRIMARY KEY, Value INTEGER DEFAULT 0);
INSERT OR IGNORE INTO Sapiens_DBUpdates (Name) VALUES ('PlayerColors');
--=======================================================================================================================
-- PLAYER COLORS
--=======================================================================================================================

--------------------------------------------------------------------------
-- Colors
--------------------------------------------------------------------------
DELETE FROM Colors WHERE Type = 'COLOR_PLAYER_ETHIOPIA_BACKGROUND';
INSERT INTO Colors (Type, Red, Green, Blue, Alpha) VALUES

-- Ethiopia
	('COLOR_PLAYER_ETHIOPIA_BACKGROUND', 0.1293, 0.3271, 0.1252, 1),

-- Cultured
	('COLOR_PLAYER_MINOR_BRATISLAVA',     0.878, 0.518, 0.678, 1),
	('COLOR_PLAYER_MINOR_BRUSSELS',       0.703, 0.466, 0.866, 1),
	('COLOR_PLAYER_MINOR_BUCHAREST',      0.682, 0.000, 1.000, 1),
	('COLOR_PLAYER_MINOR_BUENOS_AIRES',   0.678, 0.467, 1.000, 1),
	('COLOR_PLAYER_MINOR_FLORENCE',       1.000, 0.588, 0.909, 1),
	('COLOR_PLAYER_MINOR_KABUL',          0.663, 0.466, 0.678, 1),
	('COLOR_PLAYER_MINOR_KIEV',           0.516, 0.239, 1.000, 1),
	('COLOR_PLAYER_MINOR_KUALA_LUMPUR',   0.752, 0.000, 1.000, 1),
	('COLOR_PLAYER_MINOR_KYZYL',          1.000, 0.278, 0.639, 1),
	('COLOR_PLAYER_MINOR_MILAN',          0.878, 0.009, 1.000, 1),
	('COLOR_PLAYER_MINOR_MONACO',         1.000, 0.227, 1.000, 1),
	('COLOR_PLAYER_MINOR_PRAGUE',         0.552, 0.000, 1.000, 1),
	('COLOR_PLAYER_MINOR_YEREVAN',        0.878, 0.009, 0.494, 1),

-- Maritime
	('COLOR_PLAYER_MINOR_BYBLOS',         0.384, 1.000, 0.000, 1),
	('COLOR_PLAYER_MINOR_CAPE_TOWN',      0.548, 0.769, 0.000, 1),
	('COLOR_PLAYER_MINOR_MANILA',         0.000, 0.814, 0.000, 1),
	('COLOR_PLAYER_MINOR_MOMBASA',        0.000, 0.627, 0.349, 1),
	('COLOR_PLAYER_MINOR_MOGADISHU',      0.478, 1.000, 0.000, 1),
	('COLOR_PLAYER_MINOR_ORMUS',          0.341, 0.749, 0.545, 1),
	('COLOR_PLAYER_MINOR_PANAMA_CITY',    0.788, 1.000, 0.494, 1),
	('COLOR_PLAYER_MINOR_QUEBEC_CITY',    0.458, 1.000, 0.549, 1),
	('COLOR_PLAYER_MINOR_RIGA',           0.000, 1.000, 0.714, 1),
	('COLOR_PLAYER_MINOR_RAGUSA',         0.459, 1.000, 0.745, 1),
	('COLOR_PLAYER_MINOR_SYDNEY',         0.664, 1.000, 0.000, 1),
	('COLOR_PLAYER_MINOR_UR',             0.455, 1.000, 0.259, 1),
	('COLOR_PLAYER_MINOR_VANCOUVER',      0.000, 0.776, 0.427, 1),
	('COLOR_PLAYER_MINOR_WELLINGTON',     0.455, 0.737, 0.259, 1),

-- Mercantile
	('COLOR_PLAYER_MINOR_ANTWERP',        0.886, 0.743, 0.495, 1),
	('COLOR_PLAYER_MINOR_CAHOKIA',        0.717, 0.576, 0.192, 1),
	('COLOR_PLAYER_MINOR_COLOMBO',        1.000, 1.000, 0.000, 1),
	('COLOR_PLAYER_MINOR_GENOA',          1.000, 0.564, 0.000, 1),
	('COLOR_PLAYER_MINOR_HONG_KONG',      1.000, 0.745, 0.000, 1),
	('COLOR_PLAYER_MINOR_MALACCA',        1.000, 0.845, 0.000, 1),
	('COLOR_PLAYER_MINOR_MELBOURNE',      1.000, 1.000, 0.700, 1),
	('COLOR_PLAYER_MINOR_ZANZIBAR',       0.800, 0.745, 0.000, 1),
	('COLOR_PLAYER_MINOR_SAMARKAND',      0.777, 0.676, 0.000, 1),
	('COLOR_PLAYER_MINOR_TYRE',           0.878, 0.737, 0.349, 1),
	('COLOR_PLAYER_MINOR_ZURICH',         1.000, 0.925, 0.000, 1),

-- Militaristic
	('COLOR_PLAYER_MINOR_ALMATY',         0.718, 0.420, 0.318, 1),
	('COLOR_PLAYER_MINOR_BELGRADE',       1.000, 0.420, 0.318, 1),
	('COLOR_PLAYER_MINOR_BUDAPEST',       0.710, 0.298, 0.224, 1),
	('COLOR_PLAYER_MINOR_HANOI',          1.000, 0.227, 0.000, 1),
	('COLOR_PLAYER_MINOR_MBANZA_KONGO',   0.718, 0.447, 0.447, 1),
	('COLOR_PLAYER_MINOR_SIDON',          0.900, 0.337, 0.315, 1),
	('COLOR_PLAYER_MINOR_SOFIA',          0.718, 0.337, 0.337, 1),
	('COLOR_PLAYER_MINOR_VALLETTA',       0.918, 0.557, 0.487, 1),

-- Religious
	('COLOR_PLAYER_MINOR_IFE',            0.608, 0.688, 1.000, 1),
	('COLOR_PLAYER_MINOR_JERUSALEM',      0.818, 0.908, 1.000, 1),
	('COLOR_PLAYER_MINOR_KATHMANDU',      0.192, 0.518, 0.749, 1),
	('COLOR_PLAYER_MINOR_LHASA',          0.620, 0.776, 1.000, 1),
	('COLOR_PLAYER_MINOR_VATICAN_CITY',   0.437, 0.553, 1.000, 1),
	('COLOR_PLAYER_MINOR_WITTENBERG',     0.757, 0.858, 1.000, 1);

--------------------------------------------------------------------------
-- PlayerColors
--------------------------------------------------------------------------
INSERT INTO PlayerColors (Type, PrimaryColor, SecondaryColor, TextColor) VALUES

-- Cultured
	('PLAYERCOLOR_MINOR_BRATISLAVA',    'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_BRATISLAVA',    'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_BRUSSELS',      'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_BRUSSELS',      'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_BUCHAREST',     'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_BUCHAREST',     'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_BUENOS_AIRES',  'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_BUENOS_AIRES',  'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_FLORENCE',      'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_FLORENCE',      'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_KABUL',         'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_KABUL',         'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_KIEV',          'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_KIEV',          'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_KUALA_LUMPUR',  'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_KUALA_LUMPUR',  'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_KYZYL',         'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_KYZYL',         'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_MILAN',         'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_MILAN',         'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_MONACO',        'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_MONACO',        'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_PRAGUE',        'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_PRAGUE',        'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_YEREVAN',       'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_YEREVAN',       'COLOR_PLAYER_PEACH_TEXT'),

-- Maritime
	('PLAYERCOLOR_MINOR_BYBLOS',        'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_BYBLOS',        'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_CAPE_TOWN',     'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_CAPE_TOWN',     'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_MANILA',        'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_MANILA',        'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_MOMBASA',       'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_MOMBASA',       'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_MOGADISHU',     'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_MOGADISHU',     'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_ORMUS',         'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_ORMUS',         'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_PANAMA_CITY',   'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_PANAMA_CITY',   'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_QUEBEC_CITY',   'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_QUEBEC_CITY',   'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_RIGA',          'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_RIGA',          'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_RAGUSA',        'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_RAGUSA',        'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_SYDNEY',        'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_SYDNEY',        'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_UR',            'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_UR',            'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_VANCOUVER',     'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_VANCOUVER',     'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_WELLINGTON',    'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_WELLINGTON',    'COLOR_PLAYER_PEACH_TEXT'),

-- Mercantile
	('PLAYERCOLOR_MINOR_ANTWERP',       'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_ANTWERP',       'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_CAHOKIA',       'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_CAHOKIA',       'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_COLOMBO',       'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_COLOMBO',       'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_GENOA',         'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_GENOA',         'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_HONG_KONG',     'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_HONG_KONG',     'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_MALACCA',       'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_MALACCA',       'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_MELBOURNE',     'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_MELBOURNE',     'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_SAMARKAND',     'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_SAMARKAND',     'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_TYRE',          'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_TYRE',          'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_ZANZIBAR',      'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_ZANZIBAR',      'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_ZURICH',        'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_ZURICH',        'COLOR_PLAYER_PEACH_TEXT'),

-- Militaristic
	('PLAYERCOLOR_MINOR_ALMATY',        'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_ALMATY',        'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_BELGRADE',      'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_BELGRADE',      'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_BUDAPEST',      'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_BUDAPEST',      'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_HANOI',         'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_HANOI',         'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_MBANZA_KONGO',  'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_MBANZA_KONGO',  'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_SIDON',         'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_SIDON',         'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_SOFIA',         'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_SOFIA',         'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_VALLETTA',      'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_VALLETTA',      'COLOR_PLAYER_PEACH_TEXT'),

-- Religious
	('PLAYERCOLOR_MINOR_IFE',           'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_IFE',           'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_JERUSALEM',     'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_JERUSALEM',     'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_KATHMANDU',     'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_KATHMANDU',     'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_LHASA',         'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_LHASA',         'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_VATICAN_CITY',  'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_VATICAN_CITY',  'COLOR_PLAYER_PEACH_TEXT'),
	('PLAYERCOLOR_MINOR_WITTENBERG',    'COLOR_PLAYER_MINOR_ICON', 'COLOR_PLAYER_MINOR_WITTENBERG',    'COLOR_PLAYER_PEACH_TEXT');

--------------------------------------------------------------------------
-- MINOR CIV DEFAULT COLORS
--------------------------------------------------------------------------

-- Cultured
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_BRATISLAVA'   WHERE Type = 'MINOR_CIV_BRATISLAVA';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_BRUSSELS'     WHERE Type = 'MINOR_CIV_BRUSSELS';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_BUCHAREST'    WHERE Type = 'MINOR_CIV_BUCHAREST';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_BUENOS_AIRES' WHERE Type = 'MINOR_CIV_BUENOS_AIRES';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_FLORENCE'     WHERE Type = 'MINOR_CIV_FLORENCE';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_KABUL'        WHERE Type = 'MINOR_CIV_KABUL';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_KIEV'         WHERE Type = 'MINOR_CIV_KIEV';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_KUALA_LUMPUR' WHERE Type = 'MINOR_CIV_KUALA_LUMPUR';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_KYZYL'        WHERE Type = 'MINOR_CIV_KYZYL';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_MILAN'        WHERE Type = 'MINOR_CIV_MILAN';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_MONACO'       WHERE Type = 'MINOR_CIV_MONACO';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_PRAGUE'       WHERE Type = 'MINOR_CIV_PRAGUE';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_YEREVAN'      WHERE Type = 'MINOR_CIV_YEREVAN';

-- Maritime
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_BYBLOS'        WHERE Type = 'MINOR_CIV_BYBLOS';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_CAPE_TOWN'     WHERE Type = 'MINOR_CIV_CAPE_TOWN';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_MANILA'        WHERE Type = 'MINOR_CIV_MANILA';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_MOMBASA'       WHERE Type = 'MINOR_CIV_MOMBASA';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_MOGADISHU'     WHERE Type = 'MINOR_CIV_MOGADISHU';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_ORMUS'         WHERE Type = 'MINOR_CIV_ORMUS';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_PANAMA_CITY'   WHERE Type = 'MINOR_CIV_PANAMA_CITY';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_QUEBEC_CITY'   WHERE Type = 'MINOR_CIV_QUEBEC_CITY';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_RIGA'          WHERE Type = 'MINOR_CIV_RIGA';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_RAGUSA'        WHERE Type = 'MINOR_CIV_RAGUSA';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_SYDNEY'        WHERE Type = 'MINOR_CIV_SYDNEY';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_UR'            WHERE Type = 'MINOR_CIV_UR';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_VANCOUVER'     WHERE Type = 'MINOR_CIV_VANCOUVER';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_WELLINGTON'    WHERE Type = 'MINOR_CIV_WELLINGTON';

-- Mercantile
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_ANTWERP'       WHERE Type = 'MINOR_CIV_ANTWERP';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_CAHOKIA'       WHERE Type = 'MINOR_CIV_CAHOKIA';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_COLOMBO'       WHERE Type = 'MINOR_CIV_COLOMBO';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_GENOA'         WHERE Type = 'MINOR_CIV_GENOA';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_HONG_KONG'     WHERE Type = 'MINOR_CIV_HONG_KONG';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_MALACCA'       WHERE Type = 'MINOR_CIV_MALACCA';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_MELBOURNE'     WHERE Type = 'MINOR_CIV_MELBOURNE';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_SAMARKAND'     WHERE Type = 'MINOR_CIV_SAMARKAND';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_TYRE'          WHERE Type = 'MINOR_CIV_TYRE';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_ZANZIBAR'      WHERE Type = 'MINOR_CIV_ZANZIBAR';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_ZURICH'        WHERE Type = 'MINOR_CIV_ZURICH';

-- Militaristic
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_ALMATY'        WHERE Type = 'MINOR_CIV_ALMATY';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_BELGRADE'      WHERE Type = 'MINOR_CIV_BELGRADE';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_BUDAPEST'      WHERE Type = 'MINOR_CIV_BUDAPEST';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_HANOI'         WHERE Type = 'MINOR_CIV_HANOI';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_MBANZA_KONGO'  WHERE Type = 'MINOR_CIV_MBANZA_KONGO';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_SIDON'         WHERE Type = 'MINOR_CIV_SIDON';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_SOFIA'         WHERE Type = 'MINOR_CIV_SOFIA';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_VALLETTA'      WHERE Type = 'MINOR_CIV_VALLETTA';

-- Religious
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_BLUE'           WHERE Type = 'MINOR_CIV_GENEVA';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_IFE'            WHERE Type = 'MINOR_CIV_IFE';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_JERUSALEM'      WHERE Type = 'MINOR_CIV_JERUSALEM';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_KATHMANDU'      WHERE Type = 'MINOR_CIV_KATHMANDU';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_LHASA'          WHERE Type = 'MINOR_CIV_LHASA';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_VATICAN_CITY'   WHERE Type = 'MINOR_CIV_VATICAN_CITY';
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_WITTENBERG'     WHERE Type = 'MINOR_CIV_WITTENBERG';

--=======================================================================================================================
UPDATE Sapiens_DBUpdates SET Value = 1 WHERE Name = 'PlayerColors';
